version: "3.9"

services:
  bot:
    image: ghcr.io/jaskaransm/mirrorbotgo:latest
    container_name: MirrorBotGo
    restart: unless-stopped
    volumes:
      - ./config/accounts:/app/accounts:ro
      - ./config/config.json:/app/config.json:ro
      
      ## for normal google account auth
      # - ./config/credentials.json:/app/credentials.json:ro 
      # - ./config/token.json:/app/token.json:ro  
    # network_mode: container:vpn
