version: "3.9"

services:
  bot:
    image: ghcr.io/jaskaransm/mirrorbotgo
    container_name: MirrorBotGo
    # environment:
    #   - TZ=
    volumes:
      - ./config/config.json:/app/config.json:ro
      # make sure to change the download path in config.json
      # to /app/downloads if you uncomment the below line
      # - ./downloads:/app/downloads
    # network_mode: "container:vpn"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:7870/health || exit 1" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: mongo:6
    container_name: Mongo
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"
