server {
    listen 7870;
    location = /metrics {
        default_type "text/plain; version=0.0.4; charset=utf-8";
        alias /etc/sample-metrics.txt;
    }
    location / {
        return 200 "ok\n";
    }
}
