name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.1'
          cache: true

      - name: Set up Cosign
        uses: sigstore/cosign-installer@v2.8.1

      - name: Set up go work and cherry-pick anacrolix/torrent
        run: |
          cd ..
          git clone https://github.com/anacrolix/torrent -b v1.48.0
          go work init MirrorBotGo
          cd torrent
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git cherry-pick e8971ea0f1bfb26e2e05eea6e98a547dfb231bb9
          cd ..
          go work use torrent

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PUB: ${{ secrets.COSIGN_PUBLIC_KEY }}
          COSIGN_PWD: ${{ secrets.COSIGN_PASSWORD }}
